Frederikam/FredBoat

src/main/java/fredboat/FredBoat.java

Removed some useless stuff. Added an alias for ;;s that's easier to remember IMO.

Done some changes to Fredboat.java

---

src/main/java/fredboat/FredBoat.java

Ram Command

---

raw.md

Removed all mentions of the 20 song limit and added link to patreon where it previously said a patreon was coming soon:tm:

Update some things

---

src/main/java/fredboat/FredBoat.java
src/main/java/fredboat/command/fun/DogCommand.java

;;cooldog has the aliases ;;dogmeme and ;;dog
added ;;1ee7 alias to ;;leet

Added ;;cooldog command and some aliases

---

FredBoat/src/main/java/fredboat/FredBoat.java
FredBoat/src/main/java/fredboat/command/util/MusicHelpCommand.java

This command posts a list of all the commands of the music bot. I hope that the way the command is registered is good.

Added ;;mhelp and its alias ;;musichelp

---

FredBoat/src/main/java/fredboat/FredBoatBot.java
FredBoat/src/main/resources/logback.xml

Until lavaplayer is available for ARM.

Fix for Arm

---

FredBoat/src/main/java/fredboat/FredBoat.java
FredBoat/src/main/java/fredboat/command/maintenance/ShardsCommand.java

;mshards formatting

---

FredBoat/src/main/java/fredboat/audio/queue/ITrackProvider.java
FredBoat/src/main/java/fredboat/audio/queue/SimpleTrackProvider.java
FredBoat/src/main/java/fredboat/command/music/control/SkipCommand.java

This pull request is made for following issue.
https://github.com/Frederikam/FredBoat/issues/63

;;skip <range> command. #63

---

.gitignore
FredBoat/src/main/java/fredboat/command/music/info/ListCommand.java

This closes #83 make ;;queue (or some other command) show by whom a song was requested
Looks like this (new style above old style):

closes #83: make ;;queue (or some other command) show by whom a song was requested

---

selfhosting.md

docs updated for yaml files

---

selfhosting.md
systemdservice.md

added a section on running the bot as a systemd service

---

FredBoat/src/main/java/fredboat/command/music/control/PlayCommand.java

1. not in voice
2. in voice
This resolves #104

Require the User to be in a voice channel to use Play at all

---

FredBoat/src/main/java/fredboat/audio/source/PasteServiceConstants.java
FredBoat/src/main/java/fredboat/audio/source/PlaylistImportSourceManager.java

I implemented simple option to load files from pastebin.com as for #108. If other paste services are needed in the future, they could be easily added by adding a regex constant for the URL of the desired service and modifying the corresponding switch statement.

Added support for loading playlists from Pastebin

---

FredBoat/src/main/java/fredboat/FredBoatBot.java

Related to #73. Tested on macOS Sierra 10.12.2.

Fixed audio system for Mac self-hosters.

---

.gitignore
FredBoat/src/main/java/fredboat/audio/AbstractPlayer.java
FredBoat/src/main/java/fredboat/audio/GuildPlayer.java
FredBoat/src/main/java/fredboat/audio/queue/AudioTrackContext.java
FredBoat/src/main/java/fredboat/audio/queue/SimpleTrackProvider.java
FredBoat/src/main/java/fredboat/audio/queue/SplitAudioTrackContext.java
FredBoat/src/main/java/fredboat/audio/queue/TrackEndMarkerHandler.java
FredBoat/src/main/java/fredboat/command/music/control/StopCommand.java

Fix the various issues that crept up after introducing the new repeat mode.

Fix repeat and split tracks

---

FredBoat/.gitignore
FredBoat/pom.xml
FredBoat/src/main/java/fredboat/Config.java
FredBoat/src/main/java/fredboat/FredBoat.java
FredBoat/src/main/java/fredboat/command/admin/TestCommand.java
FredBoat/src/main/java/fredboat/db/DatabaseManager.java
FredBoat/src/test/java/fredboat/ProvideJDASingleton.java
FredBoat/src/test/java/fredboat/command/admin/TestCommandTest.java

Fallback to SQLite db if no jdbcUrl is given

---

FredBoat/src/main/java/fredboat/FredBoat.java
FredBoat/src/main/java/fredboat/audio/queue/AudioTrackContext.java

Do it while creating the shards, not afterwards (which can take 10 minutes)

Validate logins earlier + fix NPE

---

FredBoat/src/main/java/fredboat/command/moderation/HardbanCommand.java
FredBoat/src/main/java/fredboat/command/moderation/KickCommand.java
FredBoat/src/main/java/fredboat/commandmeta/init/MainCommandInitializer.java
FredBoat/src/main/java/fredboat/util/DiscordUtil.java

Essential moderation tool upgrades. Our staff has been asking for them, as it's hard to rightclick a spamming user's title to issue the Discord inbuilt ones.
Also softban usually deletes all messages by a user so it's impossible to manually ban someone after using softban.

Hardban and Kick Commands

---

FredBoat/src/main/java/fredboat/command/admin/ReviveCommand.java
FredBoat/src/main/java/fredboat/command/fun/LeetCommand.java
FredBoat/src/main/java/fredboat/command/fun/TalkCommand.java
FredBoat/src/main/java/fredboat/commandmeta/init/MainCommandInitializer.java
FredBoat/src/main/java/fredboat/event/EventListenerBoat.java
FredBoat/src/main/java/fredboat/event/EventLogger.java
FredBoat/src/main/java/fredboat/feature/I18n.java

Check out the commit messages for the details.

Some adjustments

---

FredBoat/src/main/java/fredboat/commandmeta/init/MainCommandInitializer.java

If `;;dealwithit` doesn't work like it's supposed to, I blame Shredder >_>(It should print `(•_•) ( •_•)>⌐■-■ (⌐■_■)`.).

Added Text Faces, moved some commands around

---

FredBoat/src/main/java/fredboat/commandmeta/init/MainCommandInitializer.java
FredBoat/src/main/java/fredboat/commandmeta/init/MusicCommandInitializer.java
README.md

Misc stuff, look at commits

---

FredBoat/src/main/java/fredboat/command/music/control/SkipCommand.java
FredBoat/src/main/java/fredboat/commandmeta/abs/Command.java

issue #189

---

FredBoat/pom.xml
FredBoat/src/main/java/fredboat/FredBoatBot.java
FredBoat/src/main/java/fredboat/audio/NativeAudioSendFactory.java
FredBoat/src/main/java/fredboat/audio/NativeAudioSendSystem.java

https://github.com/Shredder121-me/jda-nas/commit/50ea2637cdc8fc63970c3cb51ae3e6e851ec06ec
https://github.com/Shredder121-me/jda-nas/compare/master...Shredder121-me:mosh
I think this is reasonably done, although we could depend on  `jda-nas` anyway, in the off chance we're missing some dependencies.

Mosh all the open NAS PRs together

---

FredBoat/src/main/java/fredboat/command/music/info/ListCommand.java

ref: Frederikam/FredBoat-i13n#18  
fixes #247
depended on Frederikam/FredBoat-i13n#18

Show the length of a song in the "list" command

---

CONTRIBUTING.md

Stub, but how is this?
For if we also want to add screenshots for NetBeans, or make the `CONTRIBUTING.md` just really heavy on screenshots in general?

Collapse the screenshots in CONTRIBUTING.md

---

.gitignore
FredBoat/.gitignore
FredBoat/src/main/java/fredboat/db/DatabaseManager.java
FredBoat/src/main/java/fredboat/db/entity/GuildConfig.java
FredBoat/src/main/java/fredboat/db/entity/GuildPermissions.java
FredBoat/src/main/java/fredboat/db/entity/SearchResult.java
FredBoat/src/main/resources/ehcache.xml

Restrict search results cache region
Reformat and update ehcache.xml to persistence strategy
Don't persist cache to disk when the database is local
Add missing JPA annotations and Serializable implementation

Fix ehcache config

---

.gitignore
FredBoat/src/main/java/fredboat/commandmeta/CommandRegistry.java
FredBoat/src/main/java/fredboat/event/EventListenerBoat.java

This is an overly simple fix for #278
There may be some instances I am missing for this to fully work, and I have not gotten a chance to test this in a live boat just yet. I will update the PR when I've done so.

Only attempt to get lowercase command names.

---

FredBoat/src/main/java/fredboat/util/TextUtils.java

unless ofc this is intentional @napstr Kappa

Yappr fix minor issue with prefaceWith Mention/Name

---

FredBoat/src/main/java/fredboat/audio/player/GuildPlayer.java
FredBoat/src/main/java/fredboat/command/music/control/SkipCommand.java

from my testing, this works without any problems but anyone of you is welcome to test this as well
Same as PR #283
And I have a proposal, as I'm not completely confident in my Java skills I would suggest that we put this and #283 on Fredboat Cutting Edge first, at least then I have an excuse if something breaks.
fixes #269 (also at some point)

Add ;;skip overload to Skip all of a users song (;;skip @User)

---

FredBoat/pom.xml
FredBoat/src/main/java/fredboat/audio/queue/SplitAudioTrackContext.java
FredBoat/src/main/java/fredboat/command/music/control/PlaySplitCommand.java

Fix split tracks. Relies on Frederikam/Lavalink#13

---

FredBoat/pom.xml
FredBoat/src/main/java/fredboat/FredBoat.java
FredBoat/src/main/java/fredboat/command/maintenance/StatsCommand.java
FredBoat/src/main/java/fredboat/util/AppInfo.java
FredBoat/src/main/resources-filtered/app.properties

Created the branch/opened the PR to get a build from the CI.
Confirming that it's working.
The build number can be seen with the ;;mstats command (also added the lavaplayer version to it because why not).

Add build number awareness

---

CONTRIBUTING.md

Short description of core concepts of a FredBoat command + example
Explain the flow of adding new translation strings, some general rules for translations
Add invite to dev chat

[docs] Commands, Translations, Dev chat

---

FredBoat/src/main/java/fredboat/agent/VoiceChannelCleanupAgent.java
FredBoat/src/main/java/fredboat/audio/player/AbstractPlayer.java
FredBoat/src/main/java/fredboat/audio/player/GuildPlayer.java
FredBoat/src/main/java/fredboat/command/music/control/VoteSkipCommand.java
FredBoat/src/main/java/fredboat/commandmeta/init/MusicCommandInitializer.java

I've used the 500ms cooldown just like the normal `skip` command but I didn't look at rate-limiting it 
This PR is currently just to track progress & get feedback
- Get Feedback
- As I'm not very familiar with java I'm sorry for any mistakes. Please tell what is retardedly done 😄 
- Should this be a `;;config` option to decide % or disable completely?
- Or rather a feature flag?
- Both?
- Rate-limits?
DEFINITE TODOS B4 MERGE:
while I can change code numbers around I can't summon more real users to me so I would need some Test subjects 
fixes #26 (at some point)

Add Vote Skip Command

---

FredBoat/src/main/java/fredboat/command/util/MathCommand.java
FredBoat/src/main/java/fredboat/commandmeta/init/MainCommandInitializer.java

This adds a `;;math` command which can perform the next operations: addition, subtraction, multiplication, division, modulo, square root and can calculate the power of num1 to num2 and percentages.
This depends on a Fredboat-i13n PR I need to make.
Reviews would be nice.
Also yeah I fucked accounts again, GG me.

Add ;;math command

---

FredBoat/src/main/java/fredboat/api/API.java
FredBoat/src/main/java/fredboat/command/maintenance/ShardsCommand.java

Follow up of the note.
Copies aren't necessary anymore.

Cleanup copying of concurrent datastructures

---

FredBoat/src/main/java/fredboat/command/moderation/DebugCommand.java
FredBoat/src/main/java/fredboat/commandmeta/init/MusicCommandInitializer.java
FredBoat/src/main/java/fredboat/util/Emojis.java

For now this is mainly for feedback as i dont think this is optimized well. Its just so we all can see what i code at 5 in the morning

Add debug Command

---

FredBoat/src/main/java/fredboat/command/moderation/DebugCommand.java

\+ added the @ Nonnull since it was complaining

Debug command now has Debug (duh..) info about LavaLink

---

FredBoat/src/main/java/fredboat/commandmeta/init/MusicCommandInitializer.java

Added replay as an alternate command restart.

restart-alias

---

FredBoat/src/main/java/fredboat/command/admin/SetAvatarCommand.java
FredBoat/src/main/java/fredboat/commandmeta/init/MusicCommandInitializer.java

Implemented the Set Avatar command described in issue #333 
Fixes: #333 
There seems to be a limit to how many times the avatar can be changed in a set period of time (probably around 2 times every ~15 minutes).

Add set avatar command (#333)

---

FredBoat/src/main/java/fredboat/command/fun/DanceCommand.java

Rather naive way of limiting the number of dance commands, but had this one still for some time.

Limit the dance command to a number of instances

---

FredBoat/src/main/java/fredboat/audio/player/AbstractPlayer.java
FredBoat/src/main/java/fredboat/command/music/info/HistoryCommand.java
FredBoat/src/main/java/fredboat/commandmeta/init/MusicCommandInitializer.java

This is a PR which adds history command to FredBoat Music.

#314 Create a History Command

---

FredBoat/src/main/java/fredboat/command/music/info/NowplayingCommand.java
FredBoat/src/main/java/fredboat/messaging/CentralMessaging.java

Add Requester Name & Avatar to np embed

---

FredBoat/src/main/java/fredboat/command/maintenance/AudioDebugCommand.java
FredBoat/src/main/java/fredboat/command/maintenance/NodesCommand.java

fix #361 ;;adebug will return message if LL is enabled

---

FredBoat/src/main/java/fredboat/command/admin/LeaveServerCommand.java
FredBoat/src/main/java/fredboat/commandmeta/init/MainCommandInitializer.java
FredBoat/src/main/java/fredboat/commandmeta/init/MusicCommandInitializer.java

Ref issue #378, fixed PR to dev branch #379.

Adding leave server command

---

FredBoat/src/main/java/fredboat/command/music/control/PlayCommand.java

Unbox <links> for ;;play

---

FredBoat/src/main/java/fredboat/command/music/control/SelectCommand.java
FredBoat/src/main/java/fredboat/util/TextUtils.java
FredBoat/src/test/java/fredboat/util/TextUtilsTest.java

Fixes #399 
So instead of using a regex, I propose a constant-time Splitter based approach.
(The `COMMA` splitter should also be reusable for other things)

Fix for being stuck in catastrophic backtracking Resolves #399

---

FredBoat/src/main/java/fredboat/commandmeta/CommandInitializer.java
FredBoat/src/main/java/fredboat/commandmeta/abs/CommandContext.java
build.gradle

This'll work, because help command worked like this.

Add PREFIX_COMM_NAME to fix #423

---

FredBoat/src/main/java/fredboat/command/util/UserInfoCommand.java

Yeah. that if-else directive exists for a reason.

Fix isBlacklisted() target to actually target "target".

---

FredBoat/build.gradle
FredBoat/src/main/java/fredboat/db/DatabaseManager.java

Created the branch on an appropriate older commit so that we can update patron from it tomorrow.
This is the merge into dev.

Fix ssh tunnel reconnection behaviour

---

FredBoat/src/main/java/fredboat/command/info/HelloCommand.java
FredBoat/src/main/java/fredboat/commandmeta/CommandInitializer.java
FredBoat/src/main/java/fredboat/db/EntityIO.java
FredBoat/src/main/java/fredboat/db/entity/main/GuildData.java
FredBoat/src/main/java/fredboat/db/migrations/main/V4__CreateGuildData.java
FredBoat/src/main/java/fredboat/event/EventListenerBoat.java
FredBoat/src/main/resources/ehcache_main.xml

to be tested and pulled in after #436

Send hello message on joining a guild

---

FredBoat/src/main/java/fredboat/main/Launcher.java

Related: https://github.com/Frederikam/FredBoat/commit/821155dc7120f2eb6ab7bb2bb37debfb3b7752b8#r27234013

Add missing shard manager configuration

---

FredBoat/src/main/java/fredboat/command/admin/SetAvatarCommand.java

Also adds support for branding: urls, so we can use GitHub as CDN
I figured it wasn't necessary to put the main boat's avatars in there since it won't listen to the command 😂

Add shorthand values to the SetAvatarCommand

---

FredBoat/src/main/java/fredboat/command/admin/EvalCommand.java

CC @Frederikam
Behavioral change: Task will not be killed after 10 seconds, instead run until they are done. Manually killing the last task is possible through `;;eval -k`. Executing a task that automatically timeouts is still possible with `;;eval -t 10 <js code>`.
Long running tasks came in handy for some recent testing I did.
I've also been using a similarly modified eval comm on some of my other bots.

Upgrade eval comm with configurable timeout and killing of last task

---

docker-compose.yml

I'll update the guide in a moment to reflect the change, but it's mostly directed here. (`stable-v1` on QD wasn't a thing until a few days ago)
Sorry for the slight delay! 😶

Update to stable-v1 for Quarterdeck

---

FredBoat/src/main/java/fredboat/commandmeta/CommandInitializer.kt

Replace akinator command with link to aki bot

---

config/templates/docker-compose.yml
config/templates/selfhosting.yml

Update LavaLink entrypoint to 128M

---

FredBoat/src/main/java/fredboat/command/info/UptimeCommand.kt
FredBoat/src/main/java/fredboat/commandmeta/CommandInitializer.kt
FredBoat/src/main/resources/lang/en_US.properties

Also stripped some of the imports from Stats, since they seem unnecessary.

Fix #520 - Separate Uptime and Stats commands.

---

FredBoat/src/main/java/fredboat/config/property/Credentials.java
FredBoat/src/main/java/fredboat/config/property/CredentialsProperties.kt
FredBoat/src/main/java/fredboat/util/TextUtils.java
FredBoat/src/test/java/fredboat/testutil/config/MockConfig.kt

Wastebin has seen some abuse by other bots lately so I'm putting the POSTing behind authentication.

Add basic auth to wastebin POSTs

---

FredBoat/src/main/java/fredboat/config/AudioPlayerManagerConfiguration.kt
build.gradle

Trying update lavaplayer to solve #596 , but unfortunately, soundcloud still doesn't work.

Update lavaplayer, lavaplayer-ext-youtube-rotator, lavalink Version

---

config/templates/docker-compose.yml

People don't like 90Gb log files

Adjust logging for Sentinel

---

FredBoat/src/main/java/fredboat/command/info/HelpCommand.java
FredBoat/src/main/java/fredboat/command/info/InviteCommand.java
FredBoat/src/main/java/fredboat/config/applicationInfo.kt
FredBoat/src/main/java/fredboat/sentinel/wrapperEntityInterfaces.kt
FredBoat/src/main/java/fredboat/util/DiscordUtil.kt
README.md
config/templates/common.yml
config/templates/fredboat.yml

I just ran
```
rg '(?<!cdn.)discordapp.com' --pcre2 --files-with-matches | xargs gsed -i 's/discordapp\.com/discord\.com/g'
```
over all the random projects I have checked out so here's a drive-by PR changing it.

Fix Discord domain
