FredBoat/src/main/java/fredboat/Config.java, FredBoat/src/main/java/fredboat/audio/GuildPlayer.java, FredBoat/src/main/java/fredboat/audio/MusicPersistenceHandler.java, FredBoat/src/main/java/fredboat/audio/queue/AbstractTrackProvider.java, FredBoat/src/main/java/fredboat/audio/queue/AudioTrackContext.java, FredBoat/src/main/java/fredboat/audio/queue/RepeatMode.java, FredBoat/src/main/java/fredboat/audio/queue/SimpleTrackProvider.java, FredBoat/src/main/java/fredboat/command/music/control/RepeatCommand.java, FredBoat/src/main/java/fredboat/command/music/control/ReshuffleCommand.java, FredBoat/src/main/java/fredboat/command/music/info/ListCommand.java, FredBoat/src/main/java/fredboat/commandmeta/init/MusicCommandInitializer.java
related issue: #42
As specified in the issue this adds another repeat mode that will repeat the whole playlist. The handling of the shuffled list has been adapted and is also more consistent now. Additionally, it is now actually shuffled ;-) Before is was using `Collections.sort()` instead of `Collections.shuffle()`.
A message explaining the `repeat` command will be displayed if the command is used in the wrong way.
Language repo has been updated too.
=> Repeat whole playlist added

FredBoat/src/main/java/fredboat/command/moderation/LanguageCommand.java
The language codes contain underscores, so for readability it shouldn't be underlined.
=> Don't underline important text with underscores

FredBoat/credentials.yaml.example, FredBoat/src/main/java/fredboat/Config.java, FredBoat/src/main/java/fredboat/audio/AbstractPlayer.java, FredBoat/src/main/java/fredboat/audio/queue/AudioLoader.java, FredBoat/src/main/java/fredboat/audio/queue/PlaylistInfo.java, FredBoat/src/main/java/fredboat/audio/source/PlaylistImportSourceManager.java, FredBoat/src/main/java/fredboat/audio/source/PlaylistImporter.java, FredBoat/src/main/java/fredboat/audio/source/SpotifyPlaylistSourceManager.java, FredBoat/src/main/java/fredboat/util/SearchUtil.java, FredBoat/src/main/java/fredboat/util/SpotifyAPIWrapper.java
Adds Spotify playlist support
This should close #74
When reviewing this, please watch out whether this PR is in line with the existing conventions for FredBoat, especially when to do/not to do sync/async requests. I am not 100% sure I adhered to your standards, though I tried :)
I am also not sure if the Singleton pattern used in `SpotifyAPIWrapper` is the correct way to go for FredBoat in production, or if we need to shard it or whatever.
Improvements/ideas I have left after doing this:
- Make it so that `;;play <spotifyplaylist>` loads the tracks primarily from Youtube with SoundCloud as backup, and `;;sc <spotifyplaylist>` loads the tracks primarily from SoundCloud with Youtube as a backup search source. This would probably require adding more information to this call in …
=> Support for Spotify playlists by loading track through Youtube/Soundcloud

FredBoat/src/main/java/fredboat/audio/GuildPlayer.java
This helps if the bot has been moved to a channel manually (right click -> move) and the bot doesn't actually have permission to that channel.
=> Don't check if we have permission if we're already in

FredBoat/feature_flags.properties, FredBoat/pom.xml, FredBoat/src/main/java/fredboat/FredBoat.java, FredBoat/src/main/java/fredboat/api/API.java, FredBoat/src/main/java/fredboat/command/maintenance/ShardsCommand.java, FredBoat/src/main/java/fredboat/feature/togglz/FeatureFlags.java, FredBoat/src/main/java/fredboat/util/JDAUtil.java
This uses the underlying map, very carefully, which in most cases are safe enough to call.
Note that the '`pom.xml`' that gradle produces has all its dependencies set to `runtime`.
So that means that trove isn't actually a transitive (compile time) dependency of JDA.
That sucks big time, but /shrug.
=> Change the implementation of most counting commands

FredBoat/src/main/java/fredboat/event/EventListenerBoat.java
Get FredBoat to ignore messages sent by other bots.
I have not tested this code. But it should be all that is needed to stop Issue #228, unless it listens elsewhere as well.
=> Make FredBoat ignore messages from other bots

FredBoat/feature_flags.properties, FredBoat/src/main/java/fredboat/feature/togglz/FeatureFlags.java, FredBoat/src/main/java/fredboat/util/JDAUtil.java
Basically, for each user the lambda had to be bootstrapped and initialized.
In the after picture, the foreach just disappeared, because it didn't do any allocations anymore.
|  before   |  after
|---------|--------
| ![Before change][before] | ![After change][after]
[before]: https://user-images.githubusercontent.com/4105066/28748449-ac3a47de-74b8-11e7-8268-522047986ed3.png
[after]: https://user-images.githubusercontent.com/4105066/28748459-feac5bb0-74b8-11e7-8443-57a17b3bda7f.png
=> Hoist the lambda out of the loop

FredBoat/src/main/java/fredboat/command/music/control/DestroyCommand.java
I left the "destroyDenied" message untouched as it does not really affect anyone but is Bot Admins.   
This fixes #231
=> Allow BOT_ADMINs to use "Destroy" regardless of permissions

FredBoat/src/main/java/fredboat/command/moderation/ConfigCommand.java
Another one of those pebble prs.
I don't know if this is intended that config command is limited to Admins of a server only but by moving this to the perm system it's basically the same with the exception that Bot admins can also change these settings  
EDIT:
should we remove the now not used string from i13n ?
=> Use the permission system for config command

.gitignore, FredBoat/src/main/java/fredboat/util/ArgumentUtil.java
fixes #256 
I don't know if this fix is fine or if you want this fixed differently but it works  
I also added the db file to `.gitignore` since I didn't see any reason why it should not be ignored and when you run the bot with IntelliJ it generates the db file and git always wants to add it. If this is not wanted just give word and I revert the change.
also yappr (yet another pebble pr)
=> Fix perm commands search terms & Add db file to gitignore

.gitignore, FredBoat/.gitignore, FredBoat/src/main/java/fredboat/Config.java, FredBoat/src/main/java/fredboat/audio/source/SpotifyPlaylistSourceManager.java, FredBoat/src/main/java/fredboat/command/music/control/PlayCommand.java, FredBoat/src/main/java/fredboat/command/music/info/NowplayingCommand.java, FredBoat/src/main/java/fredboat/commandmeta/init/MusicCommandInitializer.java, FredBoat/src/main/java/fredboat/db/DatabaseManager.java, FredBoat/src/main/java/fredboat/db/DatabaseNotReadyException.java, FredBoat/src/main/java/fredboat/db/entity/SearchResult.java, FredBoat/src/main/java/fredboat/util/rest/SearchUtil.java, FredBoat/src/main/java/fredboat/util/rest/YoutubeAPI.java, FredBoat/src/main/java/fredboat/util/rest/YoutubeVideo.java, FredBoat/src/main/resources/ehcache.xml
This will cache all searches happening through SearchUtil for 24 hours, reducing our calls to Youtube (and Soundcloud).
Not only does it reduce our calls to Youtube, it speeds up the whole execution of the command (subjective impression here).
Part of the solution of #259
=> Cache search results + fallback to Youtube API

FredBoat/src/main/java/fredboat/commandmeta/CommandManager.java, FredBoat/src/main/java/fredboat/feature/togglz/FeatureConfig.java, FredBoat/src/main/java/fredboat/util/ratelimit/Ratelimiter.java, FredBoat/src/main/java/fredboat/util/rest/SpotifyAPIWrapper.java
This uses the holder class pattern, so the JVM can do the locking when initializing for us.
=> Make unsafe lazy initialization safe again

FredBoat/src/main/java/fredboat/command/util/UserInfoCommand.java, FredBoat/src/main/java/fredboat/util/ArgumentUtil.java
Fix for issue #279. This only applies to `;;userinfo` and `;;muserinfo` commands for now.
If other commands need this, it should be fairly easy to add.
=> UserInfoCommand will now also check bot users.

FredBoat/src/main/java/fredboat/commandmeta/CommandManager.java
I didn't test it but this is just one check b4 another so I'm 99.99999% sure nothing can blow up because of this. it's simply doing the fbh hard-coded channel/owner check b4 the perm check as we have a special message which deletes itself while the perm check doesn't
=> Check FBH hardcoeded setting b4 perm check

FredBoat/src/main/java/fredboat/command/music/control/SelectCommand.java, FredBoat/src/main/java/fredboat/command/music/info/NowplayingCommand.java, FredBoat/src/main/java/fredboat/messaging/CentralMessaging.java
~~If we encounter missing permissions during anything messaging related, we will send a message saying which permission we are missing (for example embeds, or attaching files, etc).~~
~~If we encounter missing permissions while sending a message, we will just log that to prevent a loop. (this shouldn't be happening in the first place since we don't accept commands from channels that don't allow us to write messages).~~
~~Need feedback from @Frederikam whether a) this is an acceptable flow of things and b) whether i18n is needed, and if needed whether it can be postponed (which I would prefer; a commit doing all those missing i18n todos will happen in the near future anyways).~~
Implements the behaviour of the NowplayingCommand (telling the user when there are missing permissions to …
=> Handle Insufficent permission exceptions in messaging

FredBoat/config.yaml, FredBoat/src/main/java/fredboat/Config.java
Napster and I discussed some things about the yaml files, and potentially we could also update the selfhost documentation to mention tabs are illegal in a yaml file.
So, thoughts? Should we do that instead of trying a fix-up?
=> Let the end user know that there are tabs in their yaml files

FredBoat/src/main/java/fredboat/FredBoat.java, FredBoat/src/main/java/fredboat/agent/CarbonitexAgent.java, FredBoat/src/main/java/fredboat/agent/DBConnectionWatchdogAgent.java, FredBoat/src/main/java/fredboat/agent/FredBoatAgent.java, FredBoat/src/main/java/fredboat/agent/ShardWatchdogAgent.java, FredBoat/src/main/java/fredboat/agent/VoiceChannelCleanupAgent.java, FredBoat/src/main/java/fredboat/command/maintenance/StatsCommand.java, FredBoat/src/main/java/fredboat/commandmeta/init/MusicCommandInitializer.java
I wanted to wait with this one last, but I think it's also good to get some comments/feedback in.
So here goes.
This makes the point where agents are started unified, and cleans up the `//noinspection InfiniteLoopStatement while (true) {`, each one start a Thread, (correctly) configuring it, etc. mantra.
Caveats/notes:
=> Use an executor for the processing of the agents

FredBoat/src/main/java/fredboat/FredBoat.java, FredBoat/src/main/java/fredboat/audio/player/PlayerRegistry.java, FredBoat/src/main/java/fredboat/audio/queue/MusicPersistenceHandler.java
So, in Sentry there were still some ConcurrentModificationExceptions that reminded me to fix this.
Cleanup of wrapping some return values in `synchronized/unmodifiable` counterparts still needed.
=> Use thread safe collection classes

FredBoat/src/main/java/fredboat/audio/player/AbstractPlayer.java, FredBoat/src/main/java/fredboat/audio/source/HttpSourceManager.java, ThirdPartyLicenses/APACHE2
It first tries to get audio source directly from given link like before.
If that fails and http connection has content-type text/html, it searches the html body for playlist links 
(m3u and pls) and fetches audio-source from them
Closes #43
=> Added HttpSourceManager as replacement for HttpAudioSourceManager.

FredBoat/src/main/java/fredboat/command/fun/DanceCommand.java
This uses concurrent locks, to lock across threads, instead of object monitors, which belong to a thread, and can't be queried whether they are held or not.
=> Fix dance command having more than one running instance

FredBoat/src/main/java/fredboat/command/moderation/PermissionsCommand.java, FredBoat/src/main/java/fredboat/util/ArgumentUtil.java
This is related to #227 this improves the UX by instead of saying "Nothing found for `x`" for users that are already or are not in the list respectively 
it responds with this 
While I tested the feature I noticed that ArgumentUtil#getSearchTerm() still could bug out if the search term was equal to `add` or `remove`
So the second part of this pr completely strips the raw message from the prefix/command & the add/remove argument as well as the 2 spaces.
=> small fix for the Permission command

FredBoat/src/main/java/fredboat/command/music/info/ExportCommand.java
This is actually the same as the custom identifier in the YouTube case but makes all tracks exportable.
=> Always use the track uri in the export

FredBoat/src/main/java/fredboat/FredBoat.java, FredBoat/src/main/java/fredboat/FredBoatShard.java, FredBoat/src/main/java/fredboat/util/ConnectQueue.java
This needs opinions. It looks ugly but it works.
The main issue I see here is that in case JDA changes the implementation of their ReconnectQueue we might be forced to adapt ours to update, however I didn't manage to find a more independent solution with the way the ReconnectQueue is written (running its own workers, calling protected methods).
Fixes #303
=> Use a single queue for both connecting and reconnecting Fixes #303

FredBoat/src/main/java/fredboat/event/EventListenerBoat.java, FredBoat/src/main/resources/logback.xml
Logback configuration is a stub.
So, during some debugging sessions it was hard to see what the trail of commands was.
This should make it easier to highlight what calls belong to each other.
=> Populate the MDC with debug information

FredBoat/src/main/java/fredboat/commandmeta/CommandManager.java
Adjust CommandManager.java so that the hardcoding for FredBoat Hangout now blocks all types of command (where it was previously just music commands) in channels that aren't #spam_and_music or #staff unless the user is Fre_d or Cynth
=> Adjust hardcoding for FredBoat Hangout

FredBoat/src/main/java/fredboat/command/fun/MagicCommand.java, FredBoat/src/main/java/fredboat/util/TextUtils.java
This does mean that urls aren't clickable anymore in chat.
NOTE: I made the smaller methods private, and composed them in a more encompassing method.
_had this change for some time_
=> Defuse URLs as well

FredBoat/src/main/java/fredboat/command/music/control/SelectCommand.java
Fixes issue in which all tracks would show as though they had the same length as the first one in the list
=> Fix hardcoded 0th index in time for tracks

docker-compose.yml
As https://github.com/FredBoat/fredboat.com/pull/28 is now live and people are using it, these should be changed over - especially Quarterdeck - since there's no `stable-v1` build (and never was 😆)
Since everyone following the updated guide will be aware of the selfhosting changes, and all pulling dev, I think the second change (to `dev-v3`) is fine as well. I've been running it for months.
=> Update docker-compose to match updated guide

FredBoat/src/main/java/fredboat/command/admin/EvalCommand.kt, FredBoat/src/main/java/fredboat/commandmeta/CommandInitializer.java, FredBoat/src/main/java/fredboat/main/Launcher.kt
Allows for usage in the eval command like:
```
;;eval return spring.getBean("shardManager").getGuildById("foo").getName()
```
Transforming the `Supplier<ApplicationContext>` through a kotlin -> java -> kotlin was a bit awkward, hope the code is correct.
=> Add spring application context to eval command

README.md
This would let the current default branch README on https://github.com/Frederikam/FredBoat to use relative path on the current branch instead of hardcoding to master.
(I got confused with fredboat.yaml/credential.yaml in CONTRIBUTING from the hardcoded master branch link)
=> Documentation to use relative branch link

FredBoat/Dockerfile.arm64v8, FredBoat/src/main/java/fredboat/main/Launcher.kt
I've noticed you're preparing for the Sentinel upgrade (PR #531), there are some minor JDK related settings that should be updated. I understand PRs should be made against the dev branch but I figured it would be easier to keep track of changes since your PR is merging sentinel to dev.
=> Updating Sentinel JDK to 11

config/templates/docker-compose.yml, config/templates/selfhosting.yml
Lowercase lavalink doesn't exist.
=> Update selfhosting.yml and docker-compose.yml

FredBoat/src/main/java/fredboat/config/property/AppConfig.java, FredBoat/src/main/java/fredboat/config/property/AppConfigProperties.java, FredBoat/src/main/java/fredboat/perms/PermsUtil.kt, FredBoat/src/test/java/fredboat/testutil/config/MockConfig.kt, config/templates/fredboat.yml
Fixes #551 until discordapp/discord-api-docs#787 allows querying for team members
=> [FB-551] Fix BOT_OWNER permission for Bots which belong to a Team

FredBoat/src/main/java/fredboat/command/info/StatsCommand.kt
This'll (hopefully) fix #570. 
Close #570
=> StatsCommand: Fix lagging by using cached result for guildcount

config/templates/selfhosting.yml
Sentinel-v3 is not stable and has a lot of issues with playing music and working in general.
It is a commit from November 2018 and should not be in the template files.
=> Change bot image to use dev-v4

CONTRIBUTING.md
Before: invokes the given command. Beore this test is executed
After: nvokes the given command. Before this test is executed,
=> Fixed Spelling issue

FredBoat/src/main/java/fredboat/util/TextUtils.java, config/templates/fredboat.yml
Add Hastebin as a fallback, assuming most selfhosters will not have a wastebin account.
This also fixes guilddebug, since it uses the same method.
=> Add hastebin fallback for selfhosters that do not have a wastebin account
